before:
  hooks:
  - go mod tidy
builds:
- main: ./cmd/burrow
  env:
  - CGO_ENABLED=0
  ldflags:
  - -extldflags "-static"
  - -s -w
  - -X github.com/hyperledger/burrow/project.commit={{.Commit}}
  - -X github.com/hyperledger/burrow/project.date={{.Date}}
  goos:
  - darwin
  - linux
  - freebsd
  - windows
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'